custom_users/urls.py
from django.urls import path
from . import views
from book_forum.views import BookListView

app_name = 'person'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('', views.AuthorizationView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('book_list/', BookListView.as_view(), name='book_list'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import (static)
from django.conf import settings
from book.views import post_library_view, post_librarys_detail_view
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', post_library_view),
    path('book/<int:id>/', post_librarys_detail_view),
    path('^i18n/', include('django.conf.urls.i18n')),
    path('', include('book_forum.urls')),
    path('', include('parser.urls')),
    path('', include('custom_users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/crud/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>{{book_id.name}}</h1>
<p>{{book_id.book}}</p>
<p>{{book_id.genre}}</p>
<p>{{book_id.phone_number}}</p>
<p>{{book_id.description}}</p>

<button><a href="/book_list/{{book_id.id}}/update/">Изменить</a></button>
<button><a href="/book_list/{{book_id.id}}/delete/">Удалить</a></button>
<button><a href="/create_comment/">Добавить коментарий</a></button>

<ul>
    <h2>Коментарии:</h2>
    {% for comment in book_id.comment.all %}
    <li>
        <p>{{ comment.description }}</p>
        <p>{{ comment.stars }}</p>
    </li>
    {% endfor %}
</ul>

</body>
</html>

templates/crud/book_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style_books.css' %}">
</head>
<body>

<form action="{% url 'search' %}" method="GET" role="search">
    <input type="search" type="text" name="q" placeholder="Поиск" aria-label="Search">
</form>
<br>

<form action="{% url 'person:login' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button class="logout-btn" type="submit">Выйти</button>
</form>

<button><a href="/create_book/">Добавить книгу</a></button>

{% for i in book %}
<h1>{{i.name}}</h1>
{% for tag in i.tags.all %}
<p>{{tag.name}}</p>
{% endfor %}
<button><a href="/book_list/{{i.id}}">Подробнее</a></button>
{% endfor %}

<button><a href="/everyday_genre/">Повседневность</a></button>
<button><a href="/detective_genre/">Детектив</a></button>
<button><a href="/romantic_genre/">Романтика</a></button>
<button><a href="/mystic_genre/">Мистика</a></button>

</body>
</html>

templates/crud/confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Вы точно хотите удалить эту книгу</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit">Удалить</button>
    <button><a href="/book_list/">Отмена</a></button>
</form>


</body>
</html>

templates/crud/create_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="/create_book/" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Отправить</button>
</form>

</body>
</html>

templates/crud/create_review_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="/create_review_book/" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Отправить</button>
</form>

</body>
</html>

templates/crud/edit_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Изменить</button>
</form>

</body>
</html>